- name: install c++ compiler
  yum: pkg={{item}} state=installed
  with_items:
    - gcc
    - gcc-c++

- name: create folder for nodejs
  file: path=/opt/nodejs state=directory mode=0755

- name: download nodejs 4.4
  get_url: url=http://nodejs.org/dist/v4.4.0/node-v4.4.0.tar.gz dest=/opt/nodejs/node-v4.4.0.tar.gz

- name: extract nodejs source
  command: chdir=/opt/nodejs/ tar xvf node-v4.4.0.tar.gz

- name: run configure
  command: chdir=/opt/nodejs/node-v4.4.0/ ./configure

- name: run make
  command: chdir=/opt/nodejs/node-v4.4.0/ make

- name: run make install
  command: chdir=/opt/nodejs/node-v4.4.0/ make install


